version: "3.9"
services:
  torchserve_empty:
    build:
      context: ./ts_examples/empty_model
      dockerfile: Dockerfile
    image: moono/ts_examples:empty
    shm_size: 1gb
    environment:
      - MY_TS_MODEL_LOG_LEVEL=DEBUG
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
    volumes:
      - ./ts_examples/empty_model/config.properties:/home/model-server/config.properties
      - ./ts_examples/empty_model/ts_log_config.xml:/home/model-server/ts_log_config.xml
      - ./ts_examples/empty_model/exported:/home/model-server/model-store

