version: "3.9"
services:
  # torchserve_empty:
  #   build:
  #     context: ./ts_examples/empty_model
  #     dockerfile: Dockerfile
  #   image: moono/ts_examples:empty
  #   shm_size: 1gb
  #   environment:
  #     - MY_TS_MODEL_LOG_LEVEL=DEBUG
  #     - SIMULATE_ERROR=false
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #     - 8082:8082
  #   volumes:
  #     - ./ts_examples/empty_model/config.properties:/home/model-server/config.properties
  #     - ./ts_examples/empty_model/ts_log_config.xml:/home/model-server/ts_log_config.xml
  #     - ./ts_examples/empty_model/exported:/home/model-server/model-store
  #   # command: [
  #   #   "torchserve", "--start", 
  #   #   "--models", "empty_model=empty_model.mar",
  #   #   "--ts-config", "/home/model-server/config.properties"
  #   # ]
  
  # torchserve_error:
  #   image: pytorch/torchserve:0.8.1-cpu
  #   shm_size: 1gb
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #     - 8082:8082
  #   volumes:
  #     - ./ts_examples/error_case/config.properties:/home/model-server/config.properties
  #     - ./ts_examples/error_case/exported:/home/model-server/model-store
  #   command: [
  #     "torchserve", "--start", 
  #     "--ts-config", "/home/model-server/config.properties"
  #   ]

  # torchserve_protobuf:
  #   build:
  #     context: ./ts_examples/protobuf_model
  #     dockerfile: Dockerfile
  #   image: moono/ts_examples:protobuf
  #   shm_size: 1gb
  #   environment:
  #     - MY_TS_MODEL_LOG_LEVEL=DEBUG
  #   ports:
  #     - 8080:8080
  #     - 8081:8081
  #     - 8082:8082
  #   volumes:
  #     - ./ts_examples/protobuf_model/config.properties:/home/model-server/config.properties
  #     - ./ts_examples/protobuf_model/exported:/home/model-server/model-store
  #   # command: [
  #   #   "torchserve", "--start", 
  #   #   "--models", "empty_model=empty_model.mar",
  #   #   "--ts-config", "/home/model-server/config.properties"
  #   # ]
  
  torchserve_grpc:
    build:
      context: ./ts_examples/grpc_model
      dockerfile: Dockerfile
    image: moono/ts_examples:grpc
    shm_size: 1gb
    environment:
      - MY_TS_MODEL_LOG_LEVEL=DEBUG
    ports:
      - 8080:8080
      - 8081:8081
      - 8082:8082
      - 7070:7070
      - 7071:7071
    volumes:
      - ./ts_examples/grpc_model/config.properties:/home/model-server/config.properties
      - ./ts_examples/grpc_model/exported:/home/model-server/model-store
    # command: [
    #   "torchserve", "--start", 
    #   "--models", "empty_model=empty_model.mar",
    #   "--ts-config", "/home/model-server/config.properties"
    # ]
