# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: grpc_model.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10grpc_model.proto\x12\x04test\"\xe5\x01\n\nMixedInput\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x0e\n\x06prompt\x18\x02 \x01(\t\x12\x13\n\x06height\x18\x03 \x01(\x05H\x00\x88\x01\x01\x12\x12\n\x05width\x18\x04 \x01(\x05H\x01\x88\x01\x01\x12\r\n\x05scale\x18\x05 \x01(\x02\x12#\n\x04task\x18\x06 \x01(\x0e\x32\x15.test.MixedInput.Task\x12\x12\n\nlora_names\x18\x07 \x03(\t\"-\n\x04Task\x12\x0b\n\x07TXT2IMG\x10\x00\x12\x0b\n\x07IMG2IMG\x10\x01\x12\x0b\n\x07INPAINT\x10\x02\x42\t\n\x07_heightB\x08\n\x06_width\":\n\x0bMixedOutput\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x17\n\x0fgenerated_image\x18\x02 \x01(\x0c\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'grpc_model_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MIXEDINPUT']._serialized_start=27
  _globals['_MIXEDINPUT']._serialized_end=256
  _globals['_MIXEDINPUT_TASK']._serialized_start=190
  _globals['_MIXEDINPUT_TASK']._serialized_end=235
  _globals['_MIXEDOUTPUT']._serialized_start=258
  _globals['_MIXEDOUTPUT']._serialized_end=316
# @@protoc_insertion_point(module_scope)
